ALTER TABLE horses ADD COLUMN IF NOT EXISTS breed TEXT;
ALTER TABLE horses ADD COLUMN IF NOT EXISTS color TEXT;
ALTER TABLE horses ADD COLUMN IF NOT EXISTS date_of_birth DATE;
ALTER TABLE horses ADD COLUMN IF NOT EXISTS registration_number TEXT;
ALTER TABLE horses ADD COLUMN IF NOT EXISTS photo_url TEXT;
